### ISSUE TITLE
LCD Panel Doesn't Work

### ISSUE THREAD

**Issue by Barakna** [luvies/TaledensInvManagerUpdated#32]
If I write [TIM Ore] on the LCD Panel, it'll auto un-capitalize the 'ore' bit and will not display anything on the LCD Panels. 

It'll also refuse to auto fill out the tags when, for instance , I type 'ing' it wont auto fill it as 'Ingot'.

**Comment by n1tr0-5urf3r** [comment]
You have to write [TIM INVEN:Ore] for displaying your stock. 
See also https://steamcommunity.com/sharedfiles/filedetails/?id=546909551 under "Inventory Panels"

**Comment by Barakna** [comment]
Oh I see, couldn't find any information on it, thanks for that my dude.

**Comment by Barakna** [comment]
Oh I see, couldn't find any information on it, thanks for that my dude.
